steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch', 'origin', 'main']

- name: 'gcr.io/cloud-builders/git'
  args: ['diff', '--name-only', 'origin/main..HEAD']
  id: check_changes

- name: 'python'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
      echo 'Not inside a Git repository'
      exit 1
    fi

    changes=$(cat "$BUILDER_OUTPUT" | tail -n +2)
    echo "Changes are: $changes"
