steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch', 'origin', 'main']

- name: 'gcr.io/cloud-builders/git'
  args: ['diff', '--name-only', 'origin/main..HEAD']
  id: check_changes
  entrypoint: 'bash'
  dir: '/workspace'
  waitFor:
    - '-'

- name: 'python'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
      echo 'Not inside a Git repository'
      exit 1
    fi

    changes=$(cat /workspace/check_changes)
    echo "Changes are: $changes"

options:
  machineType: N1_HIGHCPU_8
  serviceAccountEmail: fnelsonanburaj.26@gmail.com@cloud-build.iam.gserviceaccount.com
