steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'fetch'
      - 'origin'
      - 'main'

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        changes=$(git diff --name-only origin/main)
        if echo "$changes" | grep -q "^folder1/"; then
          echo "Triggered by changes in folder1"
        elif echo "$changes" | grep -q "^folder2/"; then
          echo "Triggered by changes in folder2"
        else
          echo "No changes in the specified folders"
        fi
