steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'fetch'
  - 'origin'
  - 'main'

- name: 'gcr.io/cloud-builders/git'
  args:
  - 'diff'
  - '--name-only'
  - 'origin/main'

- name: 'gcr.io/cloud-builders/bash'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if git diff --name-only origin/main | grep -q "/Demo-App/demoweb/css"; then
      echo 'hello0 css'
    elif git diff --name-only origin/main | grep -q "/Demo-App/demoweb/js"; then
      echo 'hello0 js'
    else
      echo 'no changes'
    fi
