steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'fetch'
  - 'origin'
  - 'master'

- name: 'gcr.io/cloud-builders/git'
  args:
  - 'diff'
  - '--name-only'
  - 'origin/master'

- name: 'gcr.io/cloud-builders/bash'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if git diff --name-only origin/master | grep -q "/Demo-App/demoweb/css"; then
      echo 'hello css'
    elif git diff --name-only origin/master | grep -q "/Demo-App/demoweb/js"; then
      echo 'hello js'
    else
      echo 'no changes'
    fi
