steps:
- name: python
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    if [[ -n $(git diff --name-only $COMMIT_SHA HEAD -- CLoud_Build/test/) ]]; then
      echo "Changes detected"
    else
      echo "No changes detected"
    fi