steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'fetch'
      - 'origin'
      - 'main'

  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'diff'
      - '--name-only'
      - 'origin/main'

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Changed Files: "; git diff --name-only origin/main'
