steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['fetch', 'origin', 'main']

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        changes=$(git diff --name-only origin/main)
        if echo "$changes" | grep -q "^CLoud_Build/docker/"; then
          echo "nelson"
        elif echo "$changes" | grep -q "^CLoud_Build/test/"; then
          echo "anburaj f"
        fi

  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Changes: $changes" >> output.txt
