steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'init'
  volumes:
  - name: 'workspace'
    path: '/workspace'

- name: 'gcr.io/cloud-builders/git'
  args:
  - 'fetch'
  - 'origin'
  - 'main'
  volumes:
  - name: 'workspace'
    path: '/workspace'

- name: 'gcr.io/cloud-builders/git'
  args:
  - 'diff'
  - '--name-only'
  - 'origin/main'
  volumes:
  - name: 'workspace'
    path: '/workspace'

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
      echo 'Not inside a Git repository'
      exit 1
    fi

    changes=$(git diff --name-only origin/main)
    if echo "$changes" | grep -q "/Demo-App/demoweb/css"; then
      echo 'hello css'
    elif echo "$changes" | grep -q "/Demo-App/demoweb/js"; then
      echo 'hello js'
    else
      echo 'no changes'
    fi
  volumes:
  - name: 'workspace'
    path: '/workspace'
