steps:
- name: 'python'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
      echo 'Not inside a Git repository'
      exit 1
    fi

    changes=$(git diff --name-only origin/main)
    echo "changes are $changes" 
    if echo "$changes" | grep -q "fandru//cloud_build-POC//CLoud_Build//docker"; then
      echo 'hello css'
    elif echo "$changes" | grep -q "fandru//cloud_build-POC//CLoud_Build//test"; then
      echo 'hello js'
    else
      echo 'no changes'
    fi
