version: 2.1

orbs:
  windows: circleci/windows@2.0

jobs:
  build:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout:
          path: ~/repo
      - run: choco upgrade chocolatey -y
      - run: choco search msbuild
      - run: choco install visualstudio2019buildtools 16.11.26.0
      


      

      

      

workflows:
  build:
    jobs:
      - build
