version: 2.1

orbs:
  windows: circleci/windows@2.0

jobs:
  build:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout:
          path: ~/repo
      - run: choco install msbuild --version=17.0.0 -y
      

      

workflows:
  build:
    jobs:
      - build
