version: 2.1

orbs:
  windows: circleci/windows@2.0


jobs:
  build:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout:
          path: ~/repo

      - run: |
          $currentDirectory = Get-Location
          Invoke-WebRequest -Uri 'https://aka.ms/buildtools' -OutFile "$currentDirectory\vs_buildtools.exe"
          Start-Process -Wait -FilePath "$currentDirectory\vs_buildtools.exe" -ArgumentList '--quiet --wait'

workflows:
  build:
    jobs:
      - build
