version: 2.1

orbs:
  node: circleci/node@4.2.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Build and test your project
    

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

