version: 2.1

orbs:
  windows: circleci/windows@2.0


jobs:
  build:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout:
          path: ~/repo
      - run: choco upgrade chocolatey
      - run: choco install visualstudio2022buildtools --version=117.6.2.0          
      
      

        
workflows:
  build:
    jobs:
      - build

      